
import React from 'react';
import { motion } from 'framer-motion';
import { ShieldCheck, FileText, ChevronLeft, Lock, Globe, Zap, Database, Shield, Scale } from 'lucide-react';

interface LegalPageProps {
  type: 'terms' | 'policy';
}

const LegalPage: React.FC<LegalPageProps> = ({ type }) => {
  const isTerms = type === 'terms';

  return (
    <div className="pt-32 pb-24 bg-white min-h-screen">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        
        {/* Navigation Breadcrumb */}
        <motion.button
          initial={{ opacity: 0, x: -10 }}
          animate={{ opacity: 1, x: 0 }}
          onClick={() => window.location.hash = ''}
          className="flex items-center gap-2 text-gray-400 hover:text-brand-600 transition-colors mb-12 group"
        >
          <ChevronLeft size={16} className="group-hover:-translate-x-1 transition-transform" />
          <span className="text-xs font-bold uppercase tracking-widest">Back to Home</span>
        </motion.button>

        {/* Header Section */}
        <header className="mb-16">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="flex items-center gap-4 mb-6"
          >
            <div className={`p-3 rounded-2xl ${isTerms ? 'text-gray-700' : 'text-brand-600'}`}>
              {isTerms ? <FileText size={32} /> : <ShieldCheck size={32} />}
            </div>
            <div>
              <h1 className="text-4xl md:text-5xl font-bold text-gray-900 tracking-tight">
                {isTerms ? 'Terms of Service' : 'Privacy Policy'}
              </h1>
              <p className="text-gray-400 font-medium uppercase tracking-[0.2em] text-[10px] mt-2">
                {isTerms ? 'Last Updated: December 19, 2025' : 'Effective Date: December 2025'}
              </p>
            </div>
          </motion.div>
          
          <div className="h-px w-full bg-gray-100"></div>
        </header>

        {/* Content Section */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.2 }}
          className="prose prose-brand max-w-none text-gray-600 leading-relaxed"
        >
          {isTerms ? (
            <div className="space-y-12">
              <section>
                <h2 className="text-2xl font-bold text-gray-900 mb-4 flex items-center gap-3">
                  <span className="text-brand-500 font-mono text-sm tracking-tighter">1.</span> Introduction
                </h2>
                <p>
                  These Terms of Service (the "Agreement") constitute a binding legal agreement between <strong>TaskifAI</strong> (Reg. No. SE880407637301, headquartered in Malmö, Sweden ("Supplier", "we", "us"), and you ("Customer", "User").
                </p>
                <p>
                  By accessing or using the TaskifAI platform (the "Service"), you agree to be bound by this Agreement. If you are entering into this Agreement on behalf of a company or other legal entity, you represent that you have the authority to bind such entity.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-gray-900 mb-4 flex items-center gap-3">
                  <span className="text-brand-500 font-mono text-sm tracking-tighter">2.</span> Definitions
                </h2>
                <ul className="list-disc pl-5 space-y-2">
                  <li><strong>"Service"</strong>: The TaskifAI brand intelligence operating system, including its AI agents, dashboards, and analytics tools.</li>
                  <li><strong>"Customer Data"</strong>: All proprietary metrics, sales data, trade secrets, and content uploaded by the Customer to the Service.</li>
                  <li><strong>"AI Outputs"</strong>: The insights, reports, and suggestions generated by the Service based on Customer Data.</li>
                  <li><strong>"Confidential Information"</strong>: As defined in Section 7.</li>
                </ul>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-gray-900 mb-4 flex items-center gap-3">
                  <span className="text-brand-500 font-mono text-sm tracking-tighter">3.</span> License and Use of Service
                </h2>
                <h3 className="text-lg font-bold text-gray-800 mb-2">3.1 Limited License</h3>
                <p>Subject to payment of applicable fees, we grant you a non-exclusive, non-transferable, revocable license to access and use the Service for your internal business purposes.</p>
                <h3 className="text-lg font-bold text-gray-800 mb-2 mt-4">3.2 Restrictions</h3>
                <p>You shall not:</p>
                <ul className="list-disc pl-5 space-y-2">
                  <li>Reverse engineer, decompile, or attempt to extract the source code or algorithms of the Service.</li>
                  <li>Use the Service to build a competing product.</li>
                  <li>Use the Service for any illegal or unauthorized purpose.</li>
                  <li>Input data that violates the rights of any third party or applicable laws.</li>
                </ul>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-gray-900 mb-4 flex items-center gap-3">
                  <span className="text-brand-500 font-mono text-sm tracking-tighter">4.</span> Data Sovereignty & AI Policy
                </h2>
                <div className="space-y-6">
                  <p><strong>4.1 Data Ownership:</strong> You own your data. TaskifAI claims no intellectual property rights over the Customer Data you provide.</p>
                  <p><strong>4.2 License to Process:</strong> You grant TaskifAI a worldwide, royalty-free license to access, host, and process Customer Data <em>solely</em> for the purpose of providing the Service to you.</p>
                  <p><strong>4.3 AI Training Restriction (The "No-Train" Guarantee):</strong> TaskifAI strictly covenants that <strong>Customer Data will NOT be used to train our third-party foundation models (e.g., Anthropic)</strong>. Data is processed within an isolated context window for the generation of specific outputs and is not retained by the AI provider for model improvement.</p>
                  <p><strong>4.4 EU AI Act Transparency:</strong> You acknowledge that you are interacting with an Artificial Intelligence system. AI Outputs are generated probabilistically and should be verified by human oversight before implementation.</p>
                </div>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-gray-900 mb-4 flex items-center gap-3">
                  <span className="text-brand-500 font-mono text-sm tracking-tighter">5.</span> Warranties and Disclaimers
                </h2>
                <p><strong>5.1 "As Is" Basis:</strong> The Service is provided "as is" and "as available." While we strive for high accuracy, we do not warrant that the Service will be uninterrupted or error-free.</p>
                <p><strong>5.2 AI Disclaimer:</strong> The Service utilizes artificial intelligence to generate insights. <strong>AI Outputs are suggestions only and should not be interpreted as professional financial, legal, or strategic advice.</strong> You are solely responsible for decisions made based on AI Outputs.</p>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-gray-900 mb-4 flex items-center gap-3">
                  <span className="text-brand-500 font-mono text-sm tracking-tighter">6.</span> Liability
                </h2>
                <p><strong>6.1 Limitation of Liability:</strong> To the fullest extent permitted by Swedish law, neither Party shall be liable for any indirect, incidental, or consequential damages (including loss of profits, data, or goodwill).</p>
                <p><strong>6.2 Liability Cap:</strong> Our total cumulative liability arising out of or related to this Agreement shall not exceed the total amount paid by you to TaskifAI in the twelve (12) months preceding the incident.</p>
                <p><strong>6.3 Exclusions:</strong> Nothing in this Agreement limits or excludes liability for: Death or personal injury caused by negligence; Fraud or fraudulent misrepresentation; Gross negligence (<em>grov vårdslöshet</em>) or willful misconduct (<em>uppsåt</em>); Breach of confidentiality obligations under Section 7.</p>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-gray-900 mb-4 flex items-center gap-3">
                  <span className="text-brand-500 font-mono text-sm tracking-tighter">7.</span> Confidentiality
                </h2>
                <p><strong>7.1 Definition:</strong> "Confidential Information" means any information disclosed by one Party to the other that is marked as confidential or should reasonably be understood to be confidential, including trade secrets, financial data, and technical know-how.</p>
                <p><strong>7.2 Obligations:</strong> Both Parties agree to: Hold Confidential Information in strict confidence; Not disclose such information to any third party (except to authorized employees and subprocessors bound by similar confidentiality); Use such information only to fulfill obligations under this Agreement.</p>
                <p><strong>7.3 Duration:</strong> These obligations apply during the term of this Agreement and for a period of five (5) years thereafter. For trade secrets, the confidentiality obligation is perpetual.</p>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-gray-900 mb-4 flex items-center gap-3">
                  <span className="text-brand-500 font-mono text-sm tracking-tighter">8.</span> Term and Termination
                </h2>
                <ul className="list-disc pl-5 space-y-2">
                  <li><strong>Term:</strong> This Agreement remains in effect as long as you have an active subscription.</li>
                  <li><strong>Termination for Cause:</strong> Either Party may terminate immediately if the other Party materially breaches this Agreement and fails to cure such breach within 30 days of notice.</li>
                  <li><strong>Effect of Termination:</strong> Upon termination, your right to use the Service ceases. We will delete your Customer Data in accordance with our Privacy Policy and DPA.</li>
                </ul>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-gray-900 mb-4 flex items-center gap-3">
                  <span className="text-brand-500 font-mono text-sm tracking-tighter">9.</span> Modifications to Agreement
                </h2>
                <p>
                  We may update these terms from time to time. If a revision is material, we will provide at least 30 days' notice prior to any new terms taking effect. By continuing to access or use the Service after those revisions become effective, you agree to be bound by the revised terms.
                </p>
              </section>

              <section className="border-t border-gray-100 pt-12">
                <h2 className="text-2xl font-bold text-gray-900 mb-4 flex items-center gap-3">
                  <span className="text-brand-500 font-mono text-sm tracking-tighter">10.</span> Governing Law and Dispute Resolution
                </h2>
                <p>
                  This Agreement shall be governed by the substantive laws of <strong>Sweden</strong>.
                </p>
                <p>
                  Any dispute, controversy, or claim arising out of or in connection with this Agreement shall be settled by the <strong>District Court of Malmö</strong> (Malmö tingsrätt) as the court of first instance.
                </p>
              </section>
            </div>
          ) : (
            <div className="space-y-12">
              <section>
                <h2 className="text-2xl font-bold text-gray-900 mb-4 flex items-center gap-3">
                  <span className="text-brand-500 font-mono text-sm tracking-tighter">1.</span> Introduction
                </h2>
                <p>
                  TaskifAI ("we", "us") is committed to protecting the privacy and security of your brand intelligence. This Privacy Policy outlines how we collect, use, and safeguard your information.
                </p>
                <div className="mt-4 text-sm">
                  <p className="font-bold text-gray-900 mb-1">Data Controller:</p>
                  <p>TaskifAI</p>
                  <p>Styrbordsgatan 6, 21647 Limhamn</p>
                  <p>Malmö, Sweden</p>
                  <p className="mt-2 text-brand-600 font-medium">Contact: security@taskifai.com</p>
                </div>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-gray-900 mb-4 flex items-center gap-3">
                  <span className="text-brand-500 font-mono text-sm tracking-tighter">2.</span> The Data We Collect
                </h2>
                <h3 className="text-lg font-bold text-gray-800 mb-2">2.1 Account Information</h3>
                <p>We collect data necessary to manage your account, including: Name and Email Address, Billing Information (processed via our payment provider), and Company details.</p>
                <h3 className="text-lg font-bold text-gray-800 mb-2 mt-4">2.2 Brand Intelligence Data (Client Data)</h3>
                <p>
                  This includes the proprietary datasets you upload for analysis (sales metrics, strategy docs, etc.). We process this data strictly as a <strong>Data Processor</strong> on your behalf (see Section 5).
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-gray-900 mb-4 flex items-center gap-3">
                  <span className="text-brand-500 font-mono text-sm tracking-tighter">3.</span> How We Use AI (Strict usage Policy)
                </h2>
                <p className="mb-4">We distinguish ourselves through a <strong>privacy-first AI architecture</strong>:</p>
                <ol className="list-decimal pl-5 space-y-4">
                  <li><strong>Isolation:</strong> Your data is processed in isolated logical environments.</li>
                  <li><strong>No Training:</strong> We do not use your Brand Intelligence Data to train our foundation models or the models of our third-party providers (e.g., Anthropic).</li>
                  <li><strong>Stateless Processing:</strong> When you send a query, relevant data is retrieved, anonymized where possible by our "Analyst Agent," and sent to the LLM (Large Language Model) within a transient context window. It is not stored by the LLM provider.</li>
                  <li><strong>Automated Decision Making:</strong> We do not use your personal data for automated decision-making that produces legal effects concerning you (as defined in GDPR Art. 22).</li>
                </ol>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-gray-900 mb-6 flex items-center gap-3">
                  <span className="text-brand-500 font-mono text-sm tracking-tighter">4.</span> Infrastructure and Subprocessors
                </h2>
                <p className="mb-6 text-sm">We use trusted third-party service providers to support our operations. We have Data Processing Agreements (DPAs) in place with all listed providers:</p>
                <div className="overflow-x-auto">
                  <table className="min-w-full text-sm border-t border-gray-100">
                    <thead>
                      <tr className="border-b border-gray-100">
                        <th className="px-4 py-3 text-left font-bold text-gray-900">Provider</th>
                        <th className="px-4 py-3 text-left font-bold text-gray-900">Purpose</th>
                        <th className="px-4 py-3 text-left font-bold text-gray-900">Location</th>
                        <th className="px-4 py-3 text-left font-bold text-gray-900">Transfer Mechanism</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-gray-100">
                      <tr>
                        <td className="px-4 py-4 font-bold text-gray-900">DigitalOcean</td>
                        <td className="px-4 py-4">Cloud Hosting & Infrastructure</td>
                        <td className="px-4 py-4">Europe (Germany/Netherlands)</td>
                        <td className="px-4 py-4">Intra-EEA Transfer</td>
                      </tr>
                      <tr>
                        <td className="px-4 py-4 font-bold text-gray-900">Supabase</td>
                        <td className="px-4 py-4">Database & Authentication</td>
                        <td className="px-4 py-4">Europe</td>
                        <td className="px-4 py-4">Intra-EEA Transfer</td>
                      </tr>
                      <tr>
                        <td className="px-4 py-4 font-bold text-gray-900">Anthropic</td>
                        <td className="px-4 py-4">AI Intelligence Provider</td>
                        <td className="px-4 py-4">US</td>
                        <td className="px-4 py-4">EU-US Data Privacy Framework / SCCs</td>
                      </tr>
                    </tbody>
                  </table>
                </div>
                <p className="mt-4 text-[11px] text-gray-400 italic">
                  Note: Where data is transferred to the US, we rely on the EU-US Data Privacy Framework (if applicable to the provider) or Standard Contractual Clauses (SCCs) with supplementary measures.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-gray-900 mb-4 flex items-center gap-3">
                  <span className="text-brand-500 font-mono text-sm tracking-tighter">5.</span> Security Measures
                </h2>
                <p className="mb-4">We employ enterprise-grade security including:</p>
                <ul className="space-y-4 list-none pl-0">
                  <li className="flex items-start gap-3">
                    <Shield size={18} className="text-brand-600 mt-1 flex-shrink-0" />
                    <span><strong>Encryption:</strong> AES-256 encryption for data at rest and TLS 1.3 for data in transit.</span>
                  </li>
                  <li className="flex items-start gap-3">
                    <Database size={18} className="text-brand-600 mt-1 flex-shrink-0" />
                    <span><strong>Row-Level Security (RLS):</strong> Database isolation ensuring tenants cannot access each other's data.</span>
                  </li>
                  <li className="flex items-start gap-3">
                    <Lock size={18} className="text-brand-600 mt-1 flex-shrink-0" />
                    <span><strong>Access Control:</strong> Strict internal access policies based on "least privilege."</span>
                  </li>
                  <li className="flex items-start gap-3">
                    <ShieldCheck size={18} className="text-brand-600 mt-1 flex-shrink-0" />
                    <span><strong>Audit Logging:</strong> We maintain logs of system access to detect anomalies.</span>
                  </li>
                </ul>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-gray-900 mb-4 flex items-center gap-3">
                  <span className="text-brand-500 font-mono text-sm tracking-tighter">6.</span> Your Rights (GDPR)
                </h2>
                <p className="mb-4">Under the General Data Protection Regulation (GDPR), you have the right to:</p>
                <ul className="list-disc pl-5 space-y-2">
                  <li><strong>Access:</strong> Request a copy of the personal data we hold.</li>
                  <li><strong>Rectification:</strong> Correct inaccurate data.</li>
                  <li><strong>Erasure (Right to be Forgotten):</strong> Request permanent deletion of your data/account.</li>
                  <li><strong>Portability:</strong> Receive your data in a structured, commonly used format.</li>
                  <li><strong>Object:</strong> Object to processing based on legitimate interests.</li>
                </ul>
                <p className="mt-4">To exercise these rights, contact <strong>security@taskifai.com</strong>.</p>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-gray-900 mb-4 flex items-center gap-3">
                  <span className="text-brand-500 font-mono text-sm tracking-tighter">7.</span> Data Retention
                </h2>
                <p>
                  We retain your data only as long as your account is active. Upon account cancellation, Brand Intelligence Data is deleted from our active databases within 30 days. Backups are cycled strictly according to our disaster recovery schedule and then overwritten.
                </p>
              </section>

              <section className="border-t border-gray-100 pt-12">
                <h2 className="text-2xl font-bold text-gray-900 mb-4 flex items-center gap-3">
                  <span className="text-brand-500 font-mono text-sm tracking-tighter">8.</span> Changes to this Policy
                </h2>
                <p>
                  We may update this policy to reflect changes in our technology or legal requirements. We will notify you of significant changes via email or dashboard notification.
                </p>
              </section>
            </div>
          )}
        </motion.div>
        
        {/* Footer Support Note */}
        <div className="mt-24 pt-8 border-t border-gray-100 flex flex-col sm:flex-row justify-between items-center gap-4 text-xs text-gray-400 font-medium">
          <p>TaskifAI Security Operations Center</p>
          <p>Styrbordsgatan 6, Malmö, Sweden</p>
        </div>
      </div>
    </div>
  );
};

export default LegalPage;
